image:
  magicstack/edgedb-ci:latest

variables:
  WORKON_HOME: /var/lib/venvs
  PIP_CACHE_DIR: /var/cache/pip

build:
  only:
    - master
    - ci

  tags:
    - python3

  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - build

  script:
    - export PIP_CACHE_DIR=$(pwd)/build/pip/
    - pip --quiet install vex
    - vex --python=python3 -m test pip install --quiet -U setuptools wheel pip
    - vex test pip install --quiet -U -r requirements.txt
    - vex test python setup.py -q build install
    - vex test gosu postgres:postgres pytest
    - find build -type f ! -name '*.pickle' ! -wholename 'build/pip/*' -delete && find build -type d -empty -delete
