##
# Copyright (c) 2008-2010 Sprymix Inc.
# All rights reserved.
#
# See LICENSE for details.
##


%SCHEMA semantix.utils.lang.yaml.schema.Schema
%NAME Schema
---
type: map
object: semantix.utils.config._Loader
mapping:
    =:
        &CONFIG_DATA
        object: semantix.utils.config._YamlObject
        type: choice
        choice:
            - type: map
              mapping:
                  =:
                      *CONFIG_DATA
            - type: any
