##
# Copyright (c) 2008-2010 Sprymix Inc.
# All rights reserved.
#
# See LICENSE for details.
##


%SCHEMA importkit.yaml.schema.Schema
%NAME Base
---
type: map
required: yes
mapping:
    "params": &PARAMS
        type: map
        default: {}
        mapping:
            =:
                type: map
                mapping:
                    "type":
                        type: choice
                        required: yes
                        choice:
                            - type: str
                            - type: seq
                              min-length: 1
                              max-length: 1
                              sequence:
                                - type: str

                    "default":
                        type: any

    "output": *PARAMS

    "filters":
        type: seq
        sequence:
            -
                type: map
                mapping:
                    "format":
                        type: str
                        enum: ["dict"]

    "source":
        type: any
        required: yes

    "cache":
        type: str
        enum: ["memory"]
