##
# Copyright (c) 2008-2011 Sprymix Inc.
# All rights reserved.
#
# See LICENSE for details.
##


%SCHEMA metamagic.utils.lang.yaml.schema.Schema
%NAME Schema
---
type: map
object: metamagic.utils.config.yaml.ConfigYAMLAdapter
mapping:
    =:
        &CONFIG_DATA
        object: metamagic.utils.config.yaml._YamlObject
        type: choice
        choice:
            - type: map
              mapping:
                  =:
                      *CONFIG_DATA
            - type: any
