##
# Copyright (c) 2008-2010 MagicStack Inc.
# All rights reserved.
#
# See LICENSE for details.
##


%SCHEMA importkit.yaml.schema.Schema
%NAME Schema
---
type: map
mapping:
    "fsm":
        type: map
        required: yes
        mapping:
            "start":
                type: str
                required: yes

            "transitions":
                type: map
                required: yes
                mapping:
                    =:
                        type: seq
                        required: yes
                        sequence:
                            -
                                type: map
                                required: yes
                                mapping:
                                    =:
                                        type: map
                                        required: yes
                                        mapping:
                                            "new-state":
                                                type: str
                                            "actions":
                                                type: seq
                                                sequence:
                                                    -
                                                        type: map
                                                        mapping:
                                                            =:
                                                                type: any
            "events":
                type: seq
                sequence:
                    -
                        type: map
                        mapping:
                            =:
                                type: any
